# Generated by Django 3.0.5 on 2020-05-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_remove_person_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
