# Generated by Django 3.0.5 on 2020-05-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0005_contactdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='person',
        ),
    ]
