# Generated by Django 3.0.5 on 2020-06-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0007_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvapp.Person'),
        ),
    ]
