# Generated by Django 3.0.5 on 2020-06-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0012_auto_20200605_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobbies',
            old_name='name',
            new_name='hobby_name',
        ),
    ]
