# Generated by Django 3.0.5 on 2020-06-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0013_auto_20200605_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='person',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='person',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='hobbies',
            old_name='person',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='person',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='person',
            new_name='user',
        ),
    ]
